const shopActionTypes = {
  FECHING_COLLECTIONS_START: 'FECHING_COLLECTIONS_START',
  FECHING_COLLECTIONS_SUCCESS: 'FECHING_COLLECTIONS_SUCCESS',
  FECHING_COLLECTIONS_FAILURE: 'FECHING_COLLECTIONS_FAILURE',
}
export default shopActionTypes
