const cardActionTypes = {
  TOGGLE_CARD_HIDDEN: 'TOGGLE_CARD_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  ADD_ONE_QUANTITY: 'ADD_ONE_QUANTITY',
  REMOVE_ONE_QUANTITY: 'REMOVE_ONE_QUANTITY',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_CARD: 'CLEAR_CARD',
}
export default cardActionTypes
